### PR TITLE
Using UTF-8 for reading long description

### PR DESCRIPTION
**Pull request by akaszynski**
Installing fails in CentOS Python3.6

### CODE REVIEW

**Comment by prisae** [comment]
Is that really still a problem with Python 3? Interesting!

**Comment by banesullivan** [comment]
This seems to have caused an issue on the Anaconda deployment...

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=47949

**Comment by prisae** [comment]
From the error log it looks like a Python 2 problem. I think the last line in https://github.com/conda-forge/scooby-feedstock/blob/master/.ci_support/linux_.yaml should change to something like `- '3.6'`.

**Comment by banesullivan** [comment]
So, I'm just now realizing that I need scooby to work in Python 2.7 for PVGeo because ParaView is still Python 2.7 🤦‍♂. Looks like `encoding` isn't a keyword for `open` in Python 2.7:

```zsh
(paraview) ➜  scooby git:(master) pip install -e .
Obtaining file:///Users/bane/Documents/OpenGeoVis/Software/scooby
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/bane/Documents/OpenGeoVis/Software/scooby/setup.py", line 6, in <module>
        with open("README.md", "r", encoding="utf-8") as f:
    TypeError: 'encoding' is an invalid keyword argument for this function

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /Users/bane/Documents/OpenGeoVis/Software/scooby/
You are using pip version 18.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

Looks like using [`io.open`](https://docs.python.org/2/library/io.html#io.open) is 2.7+ compatible so I just made a fix in 0a0efba

**Pull request merged**
