### PR TITLE
Add doo alias for Report 🐶

### PR DESCRIPTION
**Pull request by banesullivan**
For all the Scooby-Doo fans out there

```py
>>> import scooby
>>> scooby.doo()

--------------------------------------------------------------------------------
  Date: Thu Nov 25 09:47:50 2021 MST

                OS : Darwin
            CPU(s) : 12
           Machine : x86_64
      Architecture : 64bit
               RAM : 32.0 GiB
       Environment : Python
       File system : apfs

  Python 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:50:38)
  [Clang 11.1.0 ]

             numpy : 1.21.4
             scipy : 1.7.3
           IPython : 7.29.0
        matplotlib : 3.5.0
            scooby : 0.5.8
--------------------------------------------------------------------------------
>>>
```

cc @ocefpaf 😉

### CODE REVIEW

**Comment by banesullivan** [comment]
@prisae, and I once had a lengthy discussion about the inclusion of silly features like this. At the time we decided to keep Scooby professional with limited references to Scooby-Doo.

I think this is a fair compromise between those that want a professional tool because scooby is used in quite a lot of downstream projects and those of us who would make every single class and method named Scooby-Doo themed.

**Comment by leouieda** [comment]
I have a personal tendency to go for the more serious side for my own projects but I’m always very drawn to more whimsical projects and wish I did more of that.

**Comment by banesullivan** [comment]
Eh, I've seen you have some fun with Pooch...  ref https://github.com/fatiando/pooch/search?q=goodboy

TBH Pooch partly inspired the name of Scooby... it's fits perfectly into my grand plan to make the scientific Python stack dog themed

**Comment by leouieda** [comment]
Pooch was my attempt at whimsy 🙂 

But you may notice that newer parts of the code/docs are much more boring (but perhaps easier to follow) 🙁 

I've been leaning towards animal themed packages a bit lately myself. Even since @santisoler told me the Argentinian name for capybara is carpincho (so nice to pronounce!) I've been wanting to make a package with that name (but couldn't find a candidate yet).

**Comment by ocefpaf** [comment]
Fun fact "carpincho" also exists in Portuguese as the male capybara, capivara is only the female. (Follow me for more useless non-tech facts.)

**Comment by leouieda** [comment]
Filipe, let’s not fool anyone. We all follow you exclusively for cute baby pictures and tropical fruit caipirinhas.

@banesullivan sorry for derailing this thread completely

**Pull request merged**
