### PR TITLE
Update __init__.py with dev version

### PR DESCRIPTION
**Pull request by akaszynski**
Ideally we would use single source versioning. That's for another PR...

### CODE REVIEW

**Comment by banesullivan** [comment]
Thanks for catching this

**Comment by prisae** [comment]
Oh, I wasn't even aware we were not using single source versioning... The question is what is your preference? I use `setuptools_scm` on most of my things, I am happy to implement that. However, I am fine with anything else if you prefer other tools.

**Comment by prisae** [comment]
(`setuptools_scm` having the benefit of easily adding the git-hash for non-released version, so that a version is always unique - but then it has a little initial overhead to implement.)

**Comment by akaszynski** [comment]
> (`setuptools_scm` having the benefit of easily adding the git-hash for non-released version, so that a version is always unique - but then it has a little initial overhead to implement.)

Meh, I'm a fan of:
```py
try:
    import importlib.metadata as importlib_metadata
except ModuleNotFoundError:  # pragma: no cover
    import importlib_metadata

__version__ = importlib_metadata.version(__name__.replace(".", "-"))
```

I also think moving over to `pyproject.toml` would be fine for this project, but we don't need to change it now.

**Comment by prisae** [comment]
That is fine by me @akaszynski - again, scooby is simple enough so we keep it as simple as possible. I prefer in more complicated packages to have the git hash in the dev-versions, but for scooby that is really not necessary, so I am fine with your suggestion.

**Comment by akaszynski** [comment]
> That is fine by me @akaszynski - again, scooby is simple enough so we keep it as simple as possible. I prefer in more complicated packages to have the git hash in the dev-versions, but for scooby that is really not necessary, so I am fine with your suggestion.

Feel free to implement! Let's keep it simple, and actually, single source versioning will make things even easier to maintain.

**Comment by banesullivan** [comment]
> Let's keep it simple, and actually, single source versioning will make things even easier to maintain.

agreed

**Comment by prisae** [comment]
Actually, @akaszynski , single source versioning already, sort of, _is_ in place through bumpversion, see https://github.com/banesullivan/scooby/blob/main/.bumpversion.cfg#L1-L8 - you just didn't use it.

In this sense, @banesullivan, `setuptools_scm` would simply replace the build requirement bumpversion.

**Pull request merged**
