### PR TITLE
Fix #95

### LINKED ISSUE #95: textwrap AttributeError: 'NoneType' object has no attribute 'expandtabs'
```
$ python -c "import pyvista;print(pyvista.Report())"
  
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/scooby/report.py", line 298, in __repr__
    for txt in textwrap.wrap(self._mkl_info, self.text_width - 4):
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/textwrap.py", line 387, in wrap
    return w.wrap(text)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/textwrap.py", line 359, in wrap
    chunks = self._split_chunks(text)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/textwrap.py", line 345, in _split_chunks
    text = self._munge_whitespace(text)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/textwrap.py", line 154, in _munge_whitespace
    text = text.expandtabs(self.tabsize)
AttributeError: 'NoneType' object has no attribute 'expandtabs'
Error: Process completed with exit code 1.
```

### PR DESCRIPTION
**Pull request by prisae**
Can you test if that works in your env @banesullivan ?

Closes #95

### CODE REVIEW

**Comment by prisae** [comment]
(If possible, I'd like to get #93 in before this one.)

**Comment by banesullivan** [comment]
I'll see if I can reproduce this again... it happened in a pretty complex CI env I was debugging and ended up changing a lot. Or perhaps this might just happen anytime MKL is *not* installed? I'll find out

**Comment by prisae** [comment]
> Or perhaps this might just happen anytime MKL is not installed?

No, I checked that. If mkl is not installed, it works fine. It must be a weird setup where either `mkl.get_version_string()` or `numexpr.get_vml_version` returned `None`.

However, I think the change in this PR makes the code cleaner, and it should catch this rare case as well.

**Comment by prisae** [comment]
I'll bring that in, whether it fixes it or not, as I think it is better either way.

**Pull request merged**
