### PR TITLE
Fix extra meta order

### PR DESCRIPTION
**Pull request by banesullivan**
Fix for https://github.com/pyvista/pyvista/pull/825#issuecomment-656093781

### CODE REVIEW

**Comment by prisae** [comment]
LGTM. But the test needs to be adjusted as well.

**Comment by banesullivan** [comment]
Test fixed.

**Comment by banesullivan** [comment]
We need to patch a release for this

**Comment by akaszynski** [comment]
> We need to patch a release for this

Just pushed commit and tag for `v0.5.6`

**Pull request merged**
