### PR TITLE
Delete .travis.yml

### PR DESCRIPTION
**Pull request by banesullivan**

### CODE REVIEW

**Comment by banesullivan** [comment]
Actually, we need to make sure all of the tests from the Travis script are in the new GitHUb workflow:

```yaml
   - python -c "import scooby; print(scooby.Report(core='numpy'))"		
   - python -c "import scooby; print(scooby.Report(additional=['mock', 'foo']))"		
   - python -c "import scooby; print(scooby.Report(additional=['foo',]))"		
   - python -c "import scooby, mock; print(scooby.Report(additional=[mock,]))"		
   - python -c "import scooby, mock; print(scooby.Report(additional=mock))"		
   - python -c "import scooby, mock; print(scooby.Report(additional=mock)._repr_html_())"		
   # Test sorting		
   - python -c "import scooby; print(scooby.Report(additional=['collections', 'foo', 'aaa'], sort=True))"		
   # Test more complicated routines		
   - python -m pytest -v --cov .
```

**Comment by akaszynski** [comment]
It would seem that we should incorporate these calls into pytest rather than simply calling them from a prompt/bash so we can catch failures when the output doesn't match some expected value.

**Comment by banesullivan** [comment]
Good point, I'll see if I can get around to that in this PR over the weekend

**Comment by akaszynski** [comment]
Merged this as other branches need travis removed.  I'm keeping the branch around as to remember to add additional testing that we were doing through travis.

**Pull request merged**
