### PR TITLE
Patch for #75: File system seg fault on Windows

### LINKED ISSUE #75: Scooby upwards of version 0.5.7 segfaults Python
Coming from: https://github.com/pyvista/pyvista/issues/1961

I get an immediate segfault when importing scooby, versions 0.5.8, 0.5.9, and 0.5.10.

I'll try and see if I can narrow it down a little more.

System information, for completeness (collected with 0.5.7 ^^):

```txt
--------------------------------------------------------------------------------
  Date: Thu Dec 23 16:28:20 2021 W. Europe Standard Time

                OS : Windows
            CPU(s) : 8
           Machine : AMD64
      Architecture : 64bit
               RAM : 31.9 GiB
       Environment : Python

  Python 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:22:46)
  [MSC v.1916 64 bit (AMD64)]

             numpy : 1.20.3
             scipy : 1.7.3
           IPython : 7.30.1
        matplotlib : 3.5.1
            scooby : 0.5.7
--------------------------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by banesullivan**
I went ahead and just skipped this for Windows altogether, what do you think, @Huite and @akaszynski?

Resolves #75, resolves https://github.com/pyvista/pyvista/issues/1961

### CODE REVIEW

**Comment by akaszynski** [comment]
Agreed, especially considering the severity of this bug.

**Comment by banesullivan** [comment]
Did a little refactor too

**Comment by akaszynski** [comment]
Looks good.

**Comment by banesullivan** [comment]
Before I merge and release, @Huite, do you think you'll have a chance to double check this on your system that experiences the seg fault?

**Comment by Huite** [comment]
I don't think I can -- I won't be at the office for the next two weeks, and unfortunately I'm unable to reproduce it at home (fiddled with several USB, but to no avail). So January 11th is likely the first opportunity I'd get to test.

(Changes look good to me.)

**Comment by banesullivan** [comment]
Okay, thanks for letting me know. I'll go ahead within merging and releasing as this should simply disable the feature for Windows altogether. we can always update later to optionally enable on windows

**Comment by Huite** [comment]
Back at the office, I just tested it: the fix works, I was segfaulting on 0.5.10 and `pip install scooby=0.5.11` fixes it.

**Pull request merged**
